name: CI

on:
  push:
    branches: [ 'fix/**', 'main' ]
  pull_request:
    branches: [ main ]

jobs:
  quality-checks:
    name: Quality Checks
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'

    - name: Install dependencies  
      run: npm ci --workspaces --include-workspace-root --force

    - name: Run linter
      run: npm run lint

    - name: Build project
      run: |
        # Ensure rollup deps are installed for the build
        cd packages/core && npm ci && cd ../..
        npm run build

    - name: Check types
      run: npx tsc --noEmit

  test-matrix:
    name: Tests (${{ matrix.os }} / Node ${{ matrix.node }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node: ['18.x', '20.x']
      fail-fast: false

    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js ${{ matrix.node }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node }}
        cache: 'npm'

    - name: Install dependencies  
      run: npm ci --workspaces --include-workspace-root --force

    - name: Run unit tests
      run: |
        # Ensure rollup deps are installed for the test build
        cd packages/core && npm ci && cd ../..
        npm test

    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results-${{ matrix.os }}-node${{ matrix.node }}
        path: |
          coverage/
          test-results/

  # integration-tests:
  #   name: Integration Tests
  #   runs-on: ubuntu-latest
    
  #   services:
  #     postgres:
  #       image: postgres:16-alpine
  #       env:
  #         POSTGRES_USER: testuser
  #         POSTGRES_PASSWORD: testpass
  #         POSTGRES_DB: testdb
  #       options: >-
  #         --health-cmd pg_isready
  #         --health-interval 10s
  #         --health-timeout 5s
  #         --health-retries 5
  #       ports:
  #         - 5432:5432

  #   steps:
  #   - uses: actions/checkout@v4

  #   - name: Setup Node.js
  #     uses: actions/setup-node@v4
  #     with:
  #       node-version: '20.x'
  #       cache: 'npm'

  #   - name: Install dependencies
  #     run: npm ci --workspaces --include-workspace-root

  #   - name: Run integration tests
  #     run: npm run test:integration

  coverage:
    name: Coverage Report
    runs-on: ubuntu-latest
    needs: [quality-checks, test-matrix]
    
    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'

    - name: Install dependencies  
      run: npm ci --workspaces --include-workspace-root --force

    - name: Run tests with coverage
      run: |
        # Ensure rollup deps are installed for the test build
        cd packages/core && npm ci && cd ../..
        npm test

    - name: Check coverage thresholds
      run: npx tsx scripts/ci/coverage-check.ts --threshold 90

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
        files: ./coverage/lcov.info
        flags: unittests
        fail_ci_if_error: false

  all-checks-pass:
    name: CI Status
    runs-on: ubuntu-latest
    needs: [
      quality-checks, 
      test-matrix, 
      # integration-tests, 
      coverage
      ]
    if: always()

    steps:
    - name: Check CI results
      run: |
        echo "📊 CI Results Summary:"
        echo "======================"
        
        [ "${{ needs.quality-checks.result }}" == "success" ] && echo "✅ Quality Checks:     PASSED" || echo "❌ Quality Checks:     FAILED"
        [ "${{ needs.test-matrix.result }}" == "success" ] && echo "✅ Test Matrix:        PASSED" || echo "❌ Test Matrix:        FAILED"
        # [ "${{ needs.integration-tests.result }}" == "success" ] && echo "✅ Integration Tests:  PASSED" || echo "❌ Integration Tests:  FAILED"
        [ "${{ needs.coverage.result }}" == "success" ] && echo "✅ Coverage:           PASSED" || echo "❌ Coverage:           FAILED"
        
        echo "======================"
        
        if [ "${{ needs.quality-checks.result }}" != "success" ] || \
           [ "${{ needs.test-matrix.result }}" != "success" ] || \
          #  [ "${{ needs.integration-tests.result }}" != "success" ] || \
           [ "${{ needs.coverage.result }}" != "success" ]; then
          echo "❌ CI Failed"
          exit 1
        fi
        
        echo "✅ All CI checks passed!"